### ISSUE TITLE
Specify activerecord dependency in README and in Gemspec

### ISSUE THREAD

**Issue by bjeanes** [LendingHome/zero_downtime_migrations#4]
It looks like this might depend on AR >=5.0 but I can't be sure.

Also, you [probably don't want to commit that `Gemfile.lock`](http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/).

Thanks for the gem! I don't think I can use it yet (since I'm still on Rails 3 here) but I've thought about making something like this a few times so I'm glad someone has :)

**Comment by shuber** [comment]
Thanks for the feedback @bjeanes! This gem does not require AR >= 5. We've intentionally left the AR requirement open in the [gemspec](https://github.com/LendingHome/zero_downtime_migrations/blob/master/zero_downtime_migrations.gemspec#L16) since it's only patching methods that have been stable in AR for many versions now. Try it out with your Rails 3 app!

We've opted to commit our `Gemfile.lock` so that all our engineers can develop the gem using the same exact dependency versions. These versions are ONLY used when working on the gem directly, they have no effect when the gem is loaded into other services or libraries.

**Comment by bjeanes** [comment]
Thanks for the info. If you haven't already, it may be with documenting compatibility in the readme

**Comment by shuber** [comment]
@bjeanes Good suggestion, I'll leave this issue open until our documentation is updated, thanks!
